planner_node:
  ros__parameters:
    x: [-1000.0, 1000.0]
    y: [-1000.0, 1000.0]
    tau: [-.586, .586]
    vel: [-2.2, 2.2]
    accel: [-2.5, 2.5]
    dtau: [-.785, .785]

cev_planner_ros2_node:
  ros__parameters:
    x: [-1000.0, 1000.0]
    y: [-1000.0, 1000.0]
    tau: [-.586, .586]
    vel: [-2.2, 2.2]
    accel: [-2.5, 2.5]
    dtau: [-.785, .785]
